In [ ]:
import kagglehub
path = kagglehub.dataset_download("algozee/teenager-menthal-healy")

Collecting kagglehub
  Using cached kagglehub-1.0.0-py3-none-any.whl.metadata (40 kB)
Collecting kagglesdk<1.0,>=0.1.14 (from kagglehub)
  Using cached kagglesdk-0.1.19-py3-none-any.whl.metadata (13 kB)
Requirement already satisfied: packaging in c:\users\suf48\anaconda3\lib\site-packages (from kagglehub) (24.2)
Requirement already satisfied: pyyaml in c:\users\suf48\anaconda3\lib\site-packages (from kagglehub) (6.0.2)
Requirement already satisfied: requests in c:\users\suf48\anaconda3\lib\site-packages (from kagglehub) (2.32.3)
Requirement already satisfied: tqdm in c:\users\suf48\anaconda3\lib\site-packages (from kagglehub) (4.67.1)
Requirement already satisfied: protobuf in c:\users\suf48\anaconda3\lib\site-packages (from kagglesdk<1.0,>=0.1.14->kagglehub) (5.29.3)
Requirement already satisfied: charset-normalizer<4,>=2 in c:\users\suf48\anaconda3\lib\site-packages (from requests->kagglehub) (3.3.2)
Requirement already satisfied: idna<4,>=2.5 in c:\users\suf48\anaconda3\lib\site-packages (from requests->kagglehub) (3.7)
Requirement already satisfied: urllib3<3,>=1.21.1 in c:\users\suf48\anaconda3\lib\site-packages (from requests->kagglehub) (2.3.0)
Requirement already satisfied: certifi>=2017.4.17 in c:\users\suf48\anaconda3\lib\site-packages (from requests->kagglehub) (2025.4.26)
Requirement already satisfied: colorama in c:\users\suf48\anaconda3\lib\site-packages (from tqdm->kagglehub) (0.4.6)
Using cached kagglehub-1.0.0-py3-none-any.whl (70 kB)
Using cached kagglesdk-0.1.19-py3-none-any.whl (208 kB)
Installing collected packages: kagglesdk, kagglehub

   ---------------------------------------- 0/2 [kagglesdk]
   ---------------------------------------- 0/2 [kagglesdk]
   ---------------------------------------- 0/2 [kagglesdk]
   ---------------------------------------- 0/2 [kagglesdk]
   ---------------------------------------- 0/2 [kagglesdk]
   -------------------- ------------------- 1/2 [kagglehub]
   ---------------------------------------- 2/2 [kagglehub]

Successfully installed kagglehub-1.0.0 kagglesdk-0.1.19
Downloading to C:\Users\Suf48\.cache\kagglehub\datasets\algozee\teenager-menthal-healy\1.archive...

100%|██████████| 15.8k/15.8k [00:01<00:00, 9.41kB/s]

Extracting files...

In [3]:
import pandas as pd
import numpy as np
import os

files_list = os.listdir(path)
actual_filename = files_list[0]
full_file_path = f"{path}/{actual_filename}"
df = pd.read_csv(full_file_path)
df.head()

,age,gender,daily_social_media_hours,platform_usage,sleep_hours,screen_time_before_sleep,academic_performance,physical_activity,social_interaction_level,stress_level,anxiety_level,addiction_level,depression_label
0,14,male,7.9,Instagram,7.4,2.9,3.01,1.5,low,2,2,1,0
1,19,female,1.9,TikTok,8.0,2.9,3.22,0.8,high,8,1,10,0
2,17,female,1.3,Instagram,7.6,0.5,3.92,0.0,high,2,4,2,0
3,15,male,7.4,TikTok,6.9,1.6,3.48,0.8,medium,1,7,9,0
4,15,female,4.7,Both,4.9,3.0,2.37,1.4,medium,3,5,2,0

In [4]:
df['platform_usage'].value_counts()

platform_usage
Instagram    411
TikTok       398
Both         391
Name: count, dtype: int64

In [5]:
df['gender'].value_counts()

gender
male      615
female    585
Name: count, dtype: int64

In [6]:
df['social_interaction_level'].value_counts()

social_interaction_level
medium    416
low       415
high      369
Name: count, dtype: int64

In [7]:
from sklearn.preprocessing import LabelEncoder


a = df['gender']
b = df['platform_usage']
c = df['social_interaction_level']

gender_le = LabelEncoder()
platform_le = LabelEncoder()
Social_le = LabelEncoder()

df['gender'] = gender_le.fit_transform(a)
df['platform_usage'] = platform_le.fit_transform(b)
df['social_interaction_level'] = Social_le.fit_transform(c)

In [8]:
df

,age,gender,daily_social_media_hours,platform_usage,sleep_hours,screen_time_before_sleep,academic_performance,physical_activity,social_interaction_level,stress_level,anxiety_level,addiction_level,depression_label
0,14,1,7.9,1,7.4,2.9,3.01,1.5,1,2,2,1,0
1,19,0,1.9,2,8.0,2.9,3.22,0.8,0,8,1,10,0
2,17,0,1.3,1,7.6,0.5,3.92,0.0,0,2,4,2,0
3,15,1,7.4,2,6.9,1.6,3.48,0.8,2,1,7,9,0
4,15,0,4.7,0,4.9,3.0,2.37,1.4,2,3,5,2,0
...,...,...,...,...,...,...,...,...,...,...,...,...,...
1195,18,0,6.8,1,6.6,2.0,2.76,1.0,1,3,4,4,0
1196,16,1,2.3,0,8.0,1.9,2.12,0.4,0,7,4,4,0
1197,14,0,1.7,0,8.7,0.7,3.98,0.8,0,1,1,1,0
1198,15,1,3.9,0,8.5,2.1,3.19,0.6,0,7,9,9,0
1199,16,0,4.7,2,6.5,1.0,2.91,0.9,2,5,7,3,0

In [9]:
df['depression_label'].value_counts()

depression_label
0    1169
1      31
Name: count, dtype: int64

In [10]:
X = df.iloc[:, :-1].values
y =df.iloc[:, -1].values

In [11]:
X[0]

array([14.  ,  1.  ,  7.9 ,  1.  ,  7.4 ,  2.9 ,  3.01,  1.5 ,  1.  ,
        2.  ,  2.  ,  1.  ])

In [12]:
y[0]

np.int64(0)

In [13]:
from sklearn.model_selection import train_test_split

X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.1, random_state=42)

In [14]:
from sklearn.linear_model import LogisticRegression

model = LogisticRegression(
    max_iter=500,
    class_weight='balanced'
)
model.fit(X_train, y_train)

LogisticRegression(class_weight='balanced', max_iter=500)

In [15]:
y_pred = model.predict(X_test)

In [16]:
from sklearn.metrics import classification_report

score = classification_report(y_test, y_pred)
print("Classification reports: \n",score)

Classification reports:
               precision    recall  f1-score   support

           0       0.99      0.98      0.99       115
           1       0.67      0.80      0.73         5

    accuracy                           0.97       120
   macro avg       0.83      0.89      0.86       120
weighted avg       0.98      0.97      0.98       120

In [17]:
from sklearn.model_selection import cross_val_score

cross = cross_val_score(model, X, y, cv=3)
print("cross: ",cross)

cross:  [0.945  0.95   0.9525]

In [18]:
print("Mean: ", cross.mean())
print(f"Standard: {cross.std()}")

Mean:  0.9491666666666667
Standard: 0.0031180478223116403

In [19]:
import joblib

joblib.dump(model, 'teenager_mental_health_model.joblib')
joblib.dump(gender_le, 'gender.joblib')
joblib.dump(platform_le, 'platform.joblib')
joblib.dump(Social_le, 'social.joblib')

['social.joblib']

In [20]:
age	= 21
gender = "male"
daily_social_media_hours = 2
platform_usage	= "Instagram"
sleep_hours	= 8.0
screen_time_before_sleep = 	0.5
academic_performance	= 4.34
physical_activity	= 2.0
social_interaction_level = "medium"
stress_level	= 2
anxiety_level	= 3
addiction_level = 1
genders = gender_le.transform([gender])[0]
platform_usages = platform_le.transform([platform_usage])[0]
social_interaction_levels =Social_le.transform([social_interaction_level])[0]
test = [age, genders, daily_social_media_hours, platform_usages, sleep_hours, screen_time_before_sleep, academic_performance, physical_activity, social_interaction_levels, stress_level, anxiety_level, addiction_level]

In [21]:
model.predict([test])

array([0])